# Generated by Django 5.2.1 on 2025-06-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contrasena', models.CharField(max_length=20)),
                ('telefono', models.BigIntegerField()),
                ('imagen_perfil', models.BinaryField(blank=True, null=True)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.moneda')),
            ],
        ),
    ]
